blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.blog_detail, name='blog_detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
 

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):

    title= models.CharField(max_length=100) 
    description = models.TextField()
    added_on = models.DateField()

    # Show real names in db
    def __str__(self):
        return self.title
    
    

    # image = models.ImageField(upload_to="portfolio/images/")
    # url = models.URLField(blank=True)

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):

    title= models.CharField(max_length=100)
    image = models.ImageField(upload_to="portfolio/images")
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title
    

class Tools(models.Model):

    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="portfolio/images/tools")
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog

# Create your views here.
def all_blogs(request):
    blog_data = Blog.objects.order_by('-added_on')

    return render(request, 'blog/all_blogs.html', {"blog_data": blog_data})


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, "blog/details.html", {"blog": blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
from .models import Tools
from datetime import datetime

# Create your views here.
def home(request):
    year = datetime.now().year

    tools = Tools.objects.all()
    projects = Project.objects.all()

    return render(request, 'portfolio/home.html', {"projects": projects, "year": year,"tools": tools})

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Michael has written {{ blog_data.count }} blog{{ blog_data.count|pluralize }}</h3>

{% for blog in blog_data %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:blog_detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.added_on|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>


{% endfor %}

{% endblock %}

blog/templates/blog/details.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="container" style="text-align: center;">
    <h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>
    <br>
    <h5 class="text-center text-muted mb-5">{{ blog.added_on|date:'F jS Y' }}</h5>
    <p>{{ blog.description|safe }}</p>
</div>

{% endblock %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html>
	<head>
    {% load static %}

		<meta charset="utf-8">
		<title>🎓 Michael Haraeb</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- displays site properly based on user's device -->
		<link rel="icon" href="{% static 'portfolio/favicon.ico' %}">

		<!-- Font awesome -->
		<script src="https://kit.fontawesome.com/e8fb4d12c3.js" crossorigin="anonymous"></script>

		<!-- CSS stylesheet -->
		<link rel="stylesheet" href="{% static 'portfolio/styles.css' %}">

		<!-- Google fonts -->
	  <link rel="preconnect" href="https://fonts.googleapis.com">
	  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">

		<!-- Bootstrap 5 & 3.4-->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

	</head>
    
	<body>
 <!-- NavBar -->
		<nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'portfolio/logo_2.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Michael Haraeb's logo">

          <b><span>Michael Haraeb</span></b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% static 'portfolio/Python_ENG_2021.pdf' %}" target="blank">Resume</a>
            </li>
            <li class="nav-item">
              
              <a class="nav-link" href="{% static 'portfolio/Python_port_2021.pdf' %}" target="blank" >Currículo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.linkedin.com/in/michael-haraeb-3a500184/" target="_blank">LinkedIn</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/petos29/" target="_blank">Twitter</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/PetosPy" target="_blank">GitHub</a>
            </li>
            <li>
              <a href="{% url 'blog:all_blogs' %}" class="btn btn-outline-info">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <br>


    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <br>
    <br>

<!-- Footer Section -->
    <footer class="bg-light text-center text-white">
      <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">

          <!-- Twitter -->
          <a
            class="btn btn-floating m-1"
            style="background-color: #55acee;"
            href="https://twitter.com/petos29/"
            role="button" target="blank"
            ><i class="fab fa-twitter fa-lg"></i
          ></a>
    
          <!-- Instagram -->
          <a
            class="btn btn-floating m-1"
            style="background-color: #FF0075;"
            href="https://www.instagram.com/petos_na/"
            role="button" target="blank"
            ><i class="fab fa-instagram"></i
          ></a>
    
          <!-- Linkedin -->
          <a
            class="btn btn-floating m-1"
            style="background-color: #5a64f5;"
            href="https://www.linkedin.com/in/michael-haraeb-3a500184/"
            role="button" target="blank"
            ><i class="fab fa-linkedin-in"></i
          ></a>
          <!-- Github -->
          <a
            class="btn btn-floating m-1"
            style="background-color: #9D9D9D;"
            href="https://github.com/PetosPy"
            role="button" target="blank"
            ><i class="fab fa-github"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright --> 
      <div class="text-center p-3 text-black" style="background-color: #B5EAEA;">
        © {{ year }} Copyright:
        <a class="text-black" href="{% url 'home' %}">🎓Michael</a>
      </div>
      <!-- Copyright -->
    </footer>

  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="hero-image">
    <img src="{% static 'portfolio/petos_ss.png' %}" width="250px"  class="pro-img">
    <div class="hero-text">
      <h1 style="font-size:50px">I am Michael Haraeb</h1>
      <h3>And I'm a Python Programmer! <i class="fab fa-python"></i></h3>
    </div>
</div>

<!-- About me -->
<h2 class="mt-5" style="text-align:center">About me 😎</h2>
  <hr>
<br>
<br>  
<div class="about_me" >
    <p><h5>I am a Python developer/ programmer </h5></p>
    <p><h6>My main focus is on the Backend, with the creation of <b>APIs</b> and consumption of thrird-party APIs.
      <br>
      I also specialise in webscraping with <b>Selenium</b> and <b>Beautiful</b> soup and Web-Application testing and automation with <b>Selenium webdriver</b> and Python.
      <br>
      I am mostly self-taught with almost three years of experience with the Python programming language, 
      with which I used have developed various applications together with its Frameworks like <b>Flask</b> and <b>Django</b>. 
      This Portfolio and Blog was made with Django and is one of my first Django projects with many more to come.
    </h6></p>
</div>


<!-- Technologies -->
<h2 class="mt-5" style="text-align:center">Technologies</h2>
  <hr>
<br>
<br>

<div class="row">
    {% for project in projects %}
    
    <div class="col-lg-4 col-md-6" style="text-align:center">
      {% if project.url %}
      <a href="{{ project.url }}" target="blank">
        <img src="{{ project.image.url }}" class="img-fluid mb-2" width='100px' >
      </a>
      {% else %}
      <img  src="{{ project.image.url }}" class="img-fluid mb-2" width='100px' >

      {% endif %}
      <h6>{{ project.title }}</h6>
      <br>
  
    </div>
    {% endfor %}
</div>

<br>
<h2 class="mt-5" style="text-align:center">Tools</h2>
  <hr>
<br>
<br>

<div class="row">
    {% for tool in tools %}
    
    <div class="col-lg-4 col-md-6" style="text-align:center">
      {% if tool.url %}
      <a href="{{ tool.url }}" target="blank">
        <img src="{{ tool.image.url }}" class="img-fluid mb-2" width='100px' >
      </a>
      {% else %}
      <img  src="{{ tool.image.url }}" class="img-fluid mb-2" width='100px' >

      {% endif %}
      <h6>{{ tool.title }}</h6>
      <br>
  
    </div>
    {% endfor %}
</div>
<hr>

{% endblock %}